### ISSUE TITLE
Gap between embed and regular text

### ISSUE THREAD

**Issue by DutchPete** [Make-md/makemd#1]
Normally, the gap between a paragraph of transcluded text and a paragraph of regular text is the same as between 2 paragraphs of regular text.

![image](https://user-images.githubusercontent.com/10794265/202360109-3e83f867-3b04-4abd-8ecb-a52e51b1df5f.png)

To achieve that I use this snippet

```css
/* make gap between transcluded paragraph and normal para like between
2 normal paras */
.internal-embed.is-loaded > .markdown-embed {
    border: none;
    padding: unset;
}
.internal-embed.is-loaded > .markdown-embed > .markdown-embed-content > .markdown-rendered {
    padding: unset;
}
.internal-embed.is-loaded > .markdown-embed > .markdown-embed-content > .markdown-rendered p {
    margin-top: unset;
    margin-bottom: unset;
}
```

When Make.md is enabled, the snippet seems to be overridden..

![image](https://user-images.githubusercontent.com/10794265/202360141-56ea5706-cf1b-4c57-8008-f8431601dbe1.png)

Is there any way to correct it?
