### ISSUE TITLE
Filter not working when (property_b: true and property_b: false)

### ISSUE THREAD

**Issue by joelscampos** [Make-md/makemd#329]
Note below has 2 properties:
```
---
property_a: true
property_b: false
---

## Title
```

Filter below will not select the above note, but should:
```
---
_links: []
_filters:
  - type: all
    trueFalse: false
    filters:
      - type: frontmatter
        fType: any
        field: property_a
        fn: is
        value: "true"
      - type: frontmatter
        fType: any
        field: property_b
        fn: is
        value: "false"
_contexts: []
_sort:
  field: rank
  asc: false
  group: false
_template: ""
_templateName: ""
---
```
