### ISSUE TITLE
[Feature Request] Lucide icons for stickers

### ISSUE THREAD

**Issue by chuckharmston** [Make-md/makemd#40]
Obsidian uses the open source [Lucide icons](https://lucide.dev/). For visual consistency and noise reduction, it'd be great to be able to choose from this icon set for stickers in addition to (or instead of) emoji.

**Comment by jp-cen** [comment]
This is an upcoming improvement that's been heavily discussed in the discord. Will follow up on this once added.

**Comment by replete** [comment]
@jp-cen That's great news. 

I ended up disabling them via CSS for the time being.

Btw, you guys might like the banner adjustments I made last night:
![screencast 2023-02-15 13-25-34](https://user-images.githubusercontent.com/812139/219040270-2e67d351-b68d-40b2-b6b0-d89e5cc97f54.gif)

```css
/* @replete MAKE.MD adjustmanets 14/02/23 */

/***** HEADER ******/

/* Disable file stickers */
.mk-note-header + .mk-file-context-component .mk-file-icon {
    display:none
}

/* align field buttons */
.mk-note-header + .mk-file-context-component .mk-file-context-field-new {
    transform:translate(-7px,0);
    opacity:1;
}

/* reposition tags */
.mk-note-header + .mk-file-context-component .mk-tag-selector {
    position: absolute;
    right:10px;
    top:15px;
}

/* Make field values less visible */
.mk-file-context-value input {
    color: var(--tx3) !important
}

.mk-file-context-value input:hover {
    color:var(--tx1) !important
}
.mk-file-context-value input:focus {
    color:var(--tx1) !important
}

/* cover image gradient */
.mk-note-header::after {
    content:'';
    display: block;
    width:100%;
    height:100%;
    left:0;
    top:0;
    background:
        linear-gradient(to bottom, transparent 20%, var(--background-primary)),
        linear-gradient(to bottom, transparent 60%, var(--background-primary));
    position: absolute;
    pointer-events:none;
}

/* Disable Type '/' for commands placeholder text */
.cm-active.mk-placeholder:before {
    content:''
}

/* Disable img zoom cursor */
.mk-note-header img {
    cursor: default !important;
}

/* cssclass override: hide header until hover */
.cm-s-obsidian.hide-meta .mk-header .mk-file-context-component{
    opacity:0;
    transition: .2s opacity ease-in;
}
.cm-s-obsidian.hide-meta .mk-header:hover .mk-file-context-component{
    opacity:1;
}

/* cssclass override: short banner */
.cm-s-obsidian.banner-short .mk-note-header img{
    outline:2px solid red !important;
    height:150px !important;
}
.cm-s-obsidian.banner-short .cm-content > .mk-header .mk-spacer{
    height:50px !important
}

/* cssclass override: tall banner */
.cm-s-obsidian.banner-tall .mk-note-header img{
    outline:2px solid red !important;
    height:250px !important;
}
.cm-s-obsidian.banner-tall .cm-content > .mk-header .mk-spacer{
    height:160px !important
}

/* cssclass override: align banner to top */
.cm-s-obsidian.banner-top .mk-note-header img {
    object-position: top
}

/* cssclass override: align banner to bottom */
.cm-s-obsidian.banner-top .mk-note-header img {
    object-position: bottom
}

/* cssclass override: hide meta values in fold until focus */
.is-live-preview.meta-short .cm-content > .mk-header .mk-file-context-component,
.is-live-preview.meta-short .cm-content > .mk-header .mk-file-context-section{
    opacity:0;
    transition: .2s opacity ease-in;
}

.is-live-preview.meta-short .cm-content > .mk-header .mk-file-context-section {
    height:0;
}
.is-live-preview.meta-short .cm-content > .mk-header:hover .mk-file-context-component,
.is-live-preview.meta-short .cm-content > .mk-header:focus-within .mk-file-context-component {
    opacity:1;
}
.is-live-preview.meta-short.is-live-view .cm-content > .mk-header:hover .mk-file-context-section,
.is-live-preview.meta-short .cm-content > .mk-header:focus-within .mk-file-context-section,
.is-live-preview.meta-short .cm-content > .mk-header:hover .mk-file-context-section,
.is-live-preview.meta-short .cm-content > .mk-header:focus-within .mk-file-context-section {
    opacity:1;
    height:auto;
}

/* Fixes hover cursor target */
.cm-s-obsidian .mk-header {
    overflow:hidden;
}
```
